title: SolarWind
description: Proiecte de panouri fotovoltaice, automatizări și soluții solare
url: "https://ilascamarius.github.io"
baseurl: "/solarwind"

theme: null
plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/cayman@v0.2.0

markdown: kramdown

# Navigație
navbar-links:
  Acasă: /
  Proiecte: /proiecte/
  Contact: /contact/

  include:
  - assets/css/style.css
